name: instagram_clone
description: A pixel-perfect Instagram Feed clone built with Flutter and Riverpod.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management (Provider)
  provider: ^6.1.2

  # Image Caching
  cached_network_image: ^3.3.1

  # Shimmer loading effect
  shimmer: ^3.0.0

  # Carousel page indicators
  smooth_page_indicator: ^1.2.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/instagram_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/instagram_logo.png
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
